configuration:
  WeaveEnvironmentName: Weave 10
  ActiveDirectoryOU: ou=weave,dc=Vivika,dc=com
  CSS: \\xendeploy.vivika.com\weave\Buildkit\infrastructurehtml\style.css
  DatabaseServer: sqlv8.vivika.com
  SiteDB: ""
  LoggingDB: "" 
  MonitoringDB: ""
  Modules: Weave,WeaveHTML,WeaveRegistry
  HypervisorServer: hypervisor.vivika.com
  AdminAddress: AdminAddress.vivika.com
  ComputerList: c:\temp\computers.txt
  HypervisorSettings: \\xendeploy.vivika.com\weave\buildkit\extensions\VMware-vSphere\vdi_vsphere_2003.yaml
  Profile: profile.vivika.com
  Director: director.vivika.com
  DeploymentServer: deploy.vivika.com
  License: license.vivika.com
  WebServer: web10.vivika.com,web11.vivika.com
  Controllers: controller10.vivika.com,controller11.vivika.com 
  Servers: >
    controller10.vivika.com,controller11.vivika.com,
    profile.vivika.com, web10.vivika.com,web11.vivika.com,
    license.vivika.com,director.vivika.com
  ServersDev: ""
  ServerOU: ou=AppServers,ou=weave,dc=Vivika,dc=com