[Weave]
modules = "Weave,HTMLBuilder"

[[Weave.threads.thread]]
title = "Scheduled Tasks"
subtitle = "Local"
category = "Weave"
description = ""
descriptionpath = ""
source = ""
path = "$threadspath\\Get-ScheduledTaskModel.ps1"
Run = true
method = "command"
arguments = "-computername $computername"
PassparentSettings = ""
Properties = "*"
list = "Table"
type = "all"
OS = "all"
process = "report"

[[Weave.threads.thread]]
title = "Profile ACL Owner"
subtitle = ""
category = "Weave"
description = ""
descriptionpath = ""
source = ""
path = "$threadspath\\Test-FileServerACLModel.ps1"
Run = true
method = "command"
arguments = "-computername $ProfileServer -type owner"
PassparentSettings = ""
Properties = "*"
list = "Table"
type = "all"
OS = "all"
process = "report"

[[Weave.threads.thread]]
title = "Profile Share Stats"
subtitle = ""
category = "Windows"
description = ""
descriptionpath = ""
source = ""
path = "$threadsPath\\Test-FileServerShareStatsModel.ps1"
Run = true
method = "command"
arguments = "-computername $computername"
PassparentSettings = ""
Properties = "*"
list = "Table"
type = "all"
OS = "all"
process = "report"

[[Weave.threads.thread]]
title = "Server Info"
subtitle = ""
category = "Windows"
description = ""
descriptionpath = ""
source = ""
path = "$threadsPath\\Get-ServerStats.ps1"
Run = true
method = "command"
arguments = "-computername $computername"
PassparentSettings = ""
Properties = "*"
list = "Table"
type = "all"
OS = "all"
process = "report"
